### PR TITLE
Replace custom exceptions with standard Exception

### PR DESCRIPTION
**Pull request by SeanFeldman**
@Particular/tf-azure-host-beta @Particular/azure-host-maintainers please review

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
On a general note: shouldn't we obsolete first and then delete in next version?

**Comment by SimonCropp** [comment]
@MarcinHoppe 

> shouldn't we obsolete first and then delete in next version

Yes for APIs that we expect people to be using we want to obsolete and give a graceful transition. But these exceptions are no considered part of the programmable API, so i think it is ok to burn them in a major

**Comment by MarcinHoppe** [comment]
Thanks for clarification @SimonCropp. Makes total sense to me. Should we have this documented as a guideline somewhere in PlatDev? Looks a little bit like tribal knowledge.

**Comment by SimonCropp** [comment]
not sure how it is tribal knowledge. it is not even knowledge specific to nservicebus.

**Comment by MarcinHoppe** [comment]
It wasn't that obvious for me, hence the question about documenting it. This is not that big of a deal so I think we're fine.

Other than that the PR looks perfectly fine to me.

**Comment by SeanFeldman** [comment]
@MarcinHoppe this is what was my thought: if those exceptions are thrown and code can handle those to continue running, the the obsolete path is the right path to take (with doco, upgrade, etc.). Since these exceptions are not handled by the user code and stop execution, then what's important is the error message.

Looks like we're all in agreement. Merge? :)

**Comment by MarcinHoppe** [comment]
:+1: on merging.

**Comment by SeanFeldman** [comment]
@Particular/azure-host-maintainers @Particular/tf-azure-host-beta

**Comment by SeanFeldman** [comment]
I guess like in a theatre, we need a third bell...

:bell: @Particular/azure-host-maintainers @Particular/tf-azure-host-beta

**Pull request merged**
