### PR TITLE
RoleRecycle was still being initiated on removal of dynamic hosted endpoint from storage

### PR DESCRIPTION
**Pull request by CRuppert**
In DynamicEndpointRunner:
Despite the Process.Exited event being fired and run, the ErrorDataReceived was still executing.

In repeated tests the order of execution appears to be consistent
Process.Exited occurs and delegate is executed
Process.ErrorDataReceived occurs and delegate is executed.

When the Kill method is called on a process,  it reliably executes in that order.  Therefore we set a flag on the endpoint instance in the Exited handler indicated it was shutdown on purpose. We then check  that flag in ErrorDataReceived before allowing the Recycle request to fire.

I acknowledge that I am unsure that there is not a condition that pops ErrorDataReceived BEFORE Exited, but I was not able to cause that to occur.

### CODE REVIEW

**Comment by CRuppert** [comment]
@SeanFeldman I see that there are compilation errors from TC, but am unable to view the actual problem. I'm hoping it's not my code, as it compiles locally, but I can't tell. Is there some way for TC to surface more of the build error to github? 

Thanks!

**Comment by SimonCropp** [comment]
@CRuppert @SeanFeldman  the build server was updated to VS 2015, which uses a new version of roslyn, which was incompatible with the version of Fody used in develop of this repo. I have update fody on develop and forced a rebuild of this PR. It is not green :)

**Comment by CRuppert** [comment]
Any chance we can get this PR resolved and get a nuget pack released along the 5.x line for this?

**Comment by yvesgoeleven** [comment]
@CRuppert Thank you for the PR and sorry for taking so long to merge it in. We have been restructuring our package content and will only be able to release this once our next major goes out.

**Comment by CRuppert** [comment]
@yvesgoeleven i hate to be a bother, but now that you are in beta for the nsb 6.x line, are we any closer to getting a release for the nsb 6.2 line?

**Comment by SeanFeldman** [comment]
@CRuppert are you referring to the `support-6.2` line?

**Comment by CRuppert** [comment]
@SeanFeldman I think so? The Azure libraries being one higher than the main NSB line. I am talking about the version line that is for NSB 5.x series. So I guess the support-6.2 line?

**Comment by SeanFeldman** [comment]
@CRuppert version 6.2.5 is out
Thank you for your patience.

**Pull request merged**
