### PR TITLE
Update nuspec to target .net 4.5.2

### PR DESCRIPTION
**Pull request by WilliamBZA**
Connects to https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/20

Updates the nuspec .NET version to .NET 4.5.2

### CODE REVIEW

**Comment by SimonCropp** [comment]
re the build error. perhaps u need to update NuGetPackager to 0.5.5?

**Comment by WilliamBZA** [comment]
@SimonCropp Build passing.

**Comment by WilliamBZA** [comment]
Ping @Particular/azure-maintainers

**Comment by SeanFeldman** [comment]
Thank you @WilliamBZA

**Pull request merged**
