### PR TITLE
Update to core 6.1.0

### PR DESCRIPTION
**Pull request by andreasohlund**
WIP until the stable 6.1 is out Particular/NServiceBus#4377

### CODE REVIEW

**Comment by timbussmann** [comment]
@Particular/azure-maintainers 6.1 is now officially released. Feel free to pick up this PR and update it to the final 6.1 package. It's up to you whether you decide to only update the test projects or if you update the main projects build dependency to 6.1 too. In case of the second option, please be careful to update nuspec dependencies only if you make use of newly available 6.1 APIs.

**Comment by boblangley** [comment]
I reverted the changes to the main projects and updated the test package to 6.1.2.

**Comment by boblangley** [comment]
@Particular/azure-maintainers Please review and merge if acceptable.

**Comment by tmasternak** [comment]
@boblangley why only the test project is updated to 6.1? Do we need `.DotSettings` changes?

**Comment by andreasohlund** [comment]
>why only the test project is updated to 6.1? Do we need .DotSettings changes?

To avoid using core features added in minor versions by mistake the downstreams should only update the core ref when prepared update the nuspec to restrict the core dependency to the relevant core version.

@tmasternak does this make sense?

@bording you had some great arguments, did we document this somewhere?

cc @Particular/nservicebus-maintainers

**Comment by bording** [comment]
> @bording you had some great arguments, did we document this somewhere?

@andreasohlund I don't think so. Where do you think something like this would go?

**Comment by andreasohlund** [comment]
Perhaps
https://github.com/Particular/NServiceBus/blob/develop/MAINTAINERS.md ?

**Comment by SeanFeldman** [comment]
Merged

**Pull request merged**
